In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("results.csv", encoding="latin-1", low_memory=False)

In [3]:
df.columns

Index(['Authors', 'Title', 'Journal', 'Pub Year', 'Pub Vol', 'DOI',
       'Methodology', 'Pollinator Survey', 'Plant Survey',
       'NBN Pollinator Code', 'COL Pollinator Code', 'Pollinator Species',
       'Caste', 'NBN Plant Code', 'COL Plant Code', 'Plant Species',
       'Interactions', 'Date', 'Month', 'Year', 'Grid Letter', 'Grid Code',
       'Latitude', 'Longitude', 'Habitat', 'Pollination', 'Pollen', 'Nectar',
       'Record', 'ArticleURL'],
      dtype='object')

In [4]:
df.head()

,Authors,Title,Journal,Pub Year,Pub Vol,DOI,Methodology,Pollinator Survey,Plant Survey,NBN Pollinator Code,...,Grid Letter,Grid Code,Latitude,Longitude,Habitat,Pollination,Pollen,Nectar,Record,ArticleURL
0,M. L. Forup et al.,The restoration of plant-pollinator interactio...,Restoration Ecology,2005.0,13.0,10.1111/j.1526-100X.2005.00034.x,DO,All,All,MM0001Z100DH5JN1,...,ST,57.0,51.4200,-2.72,Rough Grassland,3.0,NaN,NaN,35435,http://www.blackwell-synergy.com/doi/abs/10.11...
1,M. L. Forup et al.,The restoration of plant-pollinator interactio...,Restoration Ecology,2005.0,13.0,10.1111/j.1526-100X.2005.00034.x,DO,All,All,NBNSYS0000005670,...,ST,57.0,51.4200,-2.72,Rough Grassland,3.0,NaN,NaN,55470,http://www.blackwell-synergy.com/doi/abs/10.11...
2,R. E. Fowler et al.,Floral abundance and resource quality influenc...,Insect Conservation and Diversity,2016.0,9.0,10.1111/icad.12197,DO,All,Group,NBNSYS0000006208,...,TQ,359094.0,50.8681,-0.07,Improved Grassland,2.0,Y,Y,34863,https://onlinelibrary.wiley.com/doi/abs/10.111...
3,M. L. Forup et al.,The restoration of plant-pollinator interactio...,Restoration Ecology,2005.0,13.0,10.1111/j.1526-100X.2005.00034.x,DO,All,All,NBNSYS0000006871,...,ST,57.0,51.4200,-2.72,Rough Grassland,3.0,NaN,NaN,48533,http://www.blackwell-synergy.com/doi/abs/10.11...
4,M. L. Forup et al.,The restoration of plant-pollinator interactio...,Restoration Ecology,2005.0,13.0,10.1111/j.1526-100X.2005.00034.x,DO,All,All,NBNSYS0000006872,...,ST,57.0,51.4200,-2.72,Rough Grassland,3.0,NaN,NaN,48572,http://www.blackwell-synergy.com/doi/abs/10.11...

In [5]:
df = df[['Pollinator Species','Plant Species','Interactions']]
df.head()

        Pollinator Species       Plant Species  Interactions
0        Euclidia glyphica    Ranunculus acris           1.0
1     Zygaena filipendulae    Knautia arvensis           1.0
2            Eristalis sp.  Crataegus monogyna           1.0
3   Platycheirus albimanus    Ranunculus acris           1.0
4  Platycheirus angustatus    Senecio jacobaea           1.0